
EXCEPTION | 2022-09-15 22:05:23 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
ETH_LOG | 2022-09-15 22:05:53 | Eth OK | br.inf.planeta.services.OneSecService$4 (run line: 685) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)

EXCEPTION | 2022-09-15 22:05:53 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-15 22:05:53 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
EXCEPTION | 2022-09-15 22:06:24 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-15 22:06:24 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
ETH_LOG | 2022-09-15 22:06:53 | Eth OK | br.inf.planeta.services.OneSecService$4 (run line: 685) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
EXCEPTION | 2022-09-15 22:06:55 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-15 22:06:55 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
DAILY_STATS | 2022-09-15 22:07:15 | {} | br.inf.planeta.services.OneSecService$4 (run line: 685) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)

VLIB_SESSION_STATS | 2022-09-15 22:07:15 | {"vmeshVersionStr":"","vlibVersionStr":"1.2.0-global","vlibId":"","vlibGitVersion":"4749542076657273696F6E206E6F7420617661696C61626C652100000000000000000000000000000000","ulibVersionStr":"1.0.1","samCsn":"58434C0062E15DF9","samBuildTime":"23:10:19","samBuildDate":"Nov 12 2019","samAtr":"3B1D97434C5F53414D00143800009000","readerModel":"SCR916","enabledKernelApps":[0,6,6,6,0,0,0,0,0,0,0,0,0,0,0,0],"emvSamConfig":"3000010545434F39","unifiedControlRequest":0,"configControlRequest":0,"enabledKernelBits":67108878,"httpReuses":0,"lastPspData":0,"lastSlsData":1663283261,"listFlags":134217732,"onlineTimeout":-7171,"pspErrors":0,"pspServerHit":0,"pspServerStatus":0,"pspUrlIndex":0,"qrcodeTransactions":0,"readerErrors":0,"emvCancellations":0,"readerSn":1599082323,"readerVersion":303,"rfu":0,"dnsErrors":0,"diskWriteFail":0,"diskReadFail":0,"emvConfirmations":0,"samErrors":0,"samResets":1,"samTtc":0,"samVersion":14356,"sessionUnifiedAdded":0,"sessionUnifiedRemoved":0,"sessionUnifiedUpdated":0,"size":477,"slsServerHit":7174,"startTime":1663283264,"tcpConnections":1,"tcpErrors":0,"tcpRetries":0,"timestamp":1663290435,"tlsHandshakeErrors":0,"transactionSuccess":0,"bytesSent":184,"emvTransactions":0,"unifiedListItems":0,"unsyncedMismatchCount":0,"updateServerStatus":1,"virtualStatus":0,"virtualTransactions":0,"bytesReceived":69,"avrListItems":0,"vlibUptime":7171,"avrGlobalCount":0,"abtTransactions":0,"vreadyStatus":1} | br.inf.planeta.services.OneSecService$4 (run line: 685) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
EXCEPTION | 2022-09-15 22:07:26 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-15 22:07:26 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
ETH_LOG | 2022-09-15 22:07:54 | Eth OK | br.inf.planeta.services.OneSecService$4 (run line: 685) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
EXCEPTION | 2022-09-15 22:07:56 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-15 22:07:56 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
EXCEPTION | 2022-09-15 22:08:00 | <<<--- | Erro ao obter hora de Servidor NTP: null[libcore.io.IoBridge.maybeThrowAfterRecvfrom(IoBridge.java:551), libcore.io.IoBridge.recvfrom(IoBridge.java:509), java.net.PlainDatagramSocketImpl.doRecv(PlainDatagramSocketImpl.java:161), java.net.PlainDatagramSocketImpl.receive(PlainDatagramSocketImpl.java:169), java.net.DatagramSocket.receive(DatagramSocket.java:250), org.apache.commons.net.ntp.NTPUDPClient.getTime(NTPUDPClient.java:89), br.inf.planeta.pedagio.DateTimeNTPServer.setSystemDateTimeWithDateTimeFromNTPServer(DateTimeNTPServer.java:25), br.inf.planeta.services.OneSecService$1.run(OneSecService.java:189), java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422), java.util.concurrent.FutureTask.run(FutureTask.java:237), java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152), java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | br.inf.planeta.services.OneSecService$1 (run line: 189) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (run line: 237)
REST | 2022-09-15 22:08:08 | --->>> | Response: {"VersaoSoftware":"9.6.5","Antenas":[{"VersaoSoftware":"0000012F","NomeLeitor":"SCR916","NumeroSerieLeitor":"5F500F53","NumLeitor":0,"BlStatusLeitor":1}],"ContadoresInternos":[0,0],"DataHora":"2022-09-15 22:08:08","NumeroSerieSLM":"8000B0CC","SLMTempoExecucao":7239,"AndroidTempoExecucao":7262} | br.inf.planeta.services.OneSecService$4 (run line: 685) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
EXCEPTION | 2022-09-15 22:08:27 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-15 22:08:27 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
ETH_LOG | 2022-09-15 22:08:54 | Eth OK | br.inf.planeta.services.OneSecService$4 (run line: 685) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
EXCEPTION | 2022-09-15 22:08:57 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-15 22:08:57 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
EXCEPTION | 2022-09-15 22:09:28 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-15 22:09:28 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
ETH_LOG | 2022-09-15 22:09:55 | Eth OK | br.inf.planeta.services.OneSecService$4 (run line: 685) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
EXCEPTION | 2022-09-15 22:09:59 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-15 22:09:59 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
EXCEPTION | 2022-09-15 22:10:30 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-15 22:10:30 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
ETH_LOG | 2022-09-15 22:10:55 | Eth OK | br.inf.planeta.services.OneSecService$4 (run line: 685) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
EXCEPTION | 2022-09-15 22:11:01 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-15 22:11:01 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
EXCEPTION | 2022-09-15 22:11:32 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-15 22:11:32 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
ETH_LOG | 2022-09-15 22:11:56 | Eth OK | br.inf.planeta.services.OneSecService$4 (run line: 685) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
EXCEPTION | 2022-09-15 22:12:02 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-15 22:12:02 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
EXCEPTION | 2022-09-15 22:12:33 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-15 22:12:33 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
ETH_LOG | 2022-09-15 22:12:57 | Eth OK | br.inf.planeta.services.OneSecService$4 (run line: 685) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
EXCEPTION | 2022-09-15 22:13:00 | <<<--- | Erro ao obter hora de Servidor NTP: null[libcore.io.IoBridge.maybeThrowAfterRecvfrom(IoBridge.java:551), libcore.io.IoBridge.recvfrom(IoBridge.java:509), java.net.PlainDatagramSocketImpl.doRecv(PlainDatagramSocketImpl.java:161), java.net.PlainDatagramSocketImpl.receive(PlainDatagramSocketImpl.java:169), java.net.DatagramSocket.receive(DatagramSocket.java:250), org.apache.commons.net.ntp.NTPUDPClient.getTime(NTPUDPClient.java:89), br.inf.planeta.pedagio.DateTimeNTPServer.setSystemDateTimeWithDateTimeFromNTPServer(DateTimeNTPServer.java:25), br.inf.planeta.services.OneSecService$1.run(OneSecService.java:189), java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422), java.util.concurrent.FutureTask.run(FutureTask.java:237), java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152), java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | br.inf.planeta.services.OneSecService$1 (run line: 189) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (run line: 237)
EXCEPTION | 2022-09-15 22:13:04 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-15 22:13:04 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
REST | 2022-09-15 22:13:09 | --->>> | Response: {"VersaoSoftware":"9.6.5","Antenas":[{"VersaoSoftware":"0000012F","NomeLeitor":"SCR916","NumeroSerieLeitor":"5F500F53","NumLeitor":0,"BlStatusLeitor":1}],"ContadoresInternos":[0,0],"DataHora":"2022-09-15 22:13:09","NumeroSerieSLM":"8000B0CC","SLMTempoExecucao":7540,"AndroidTempoExecucao":7563} | br.inf.planeta.services.OneSecService$4 (run line: 685) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
EXCEPTION | 2022-09-15 22:13:35 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-15 22:13:35 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
ETH_LOG | 2022-09-15 22:13:57 | Eth OK | br.inf.planeta.services.OneSecService$4 (run line: 685) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
EXCEPTION | 2022-09-15 22:14:05 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-15 22:14:05 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
EXCEPTION | 2022-09-15 22:14:36 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-15 22:14:36 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
ETH_LOG | 2022-09-15 22:14:58 | Eth OK | br.inf.planeta.services.OneSecService$4 (run line: 685) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
EXCEPTION | 2022-09-15 22:15:07 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-15 22:15:07 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
EXCEPTION | 2022-09-15 22:15:38 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-15 22:15:38 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
ETH_LOG | 2022-09-15 22:15:59 | Eth OK | br.inf.planeta.services.OneSecService$4 (run line: 685) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
EXCEPTION | 2022-09-15 22:16:09 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-15 22:16:09 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
EXCEPTION | 2022-09-15 22:16:40 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-15 22:16:40 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
ETH_LOG | 2022-09-15 22:17:00 | Eth OK | br.inf.planeta.services.OneSecService$4 (run line: 685) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
EXCEPTION | 2022-09-15 22:17:11 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-15 22:17:11 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
DAILY_STATS | 2022-09-15 22:17:15 | {} | br.inf.planeta.services.OneSecService$4 (run line: 685) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)

VLIB_SESSION_STATS | 2022-09-15 22:17:15 | {"vmeshVersionStr":"","vlibVersionStr":"1.2.0-global","vlibId":"","vlibGitVersion":"4749542076657273696F6E206E6F7420617661696C61626C652100000000000000000000000000000000","ulibVersionStr":"1.0.1","samCsn":"58434C0062E15DF9","samBuildTime":"23:10:19","samBuildDate":"Nov 12 2019","samAtr":"3B1D97434C5F53414D00143800009000","readerModel":"SCR916","enabledKernelApps":[0,6,6,6,0,0,0,0,0,0,0,0,0,0,0,0],"emvSamConfig":"3000010545434F39","unifiedControlRequest":0,"configControlRequest":0,"enabledKernelBits":67108878,"httpReuses":0,"lastPspData":0,"lastSlsData":1663283261,"listFlags":134217732,"onlineTimeout":-7771,"pspErrors":0,"pspServerHit":0,"pspServerStatus":0,"pspUrlIndex":0,"qrcodeTransactions":0,"readerErrors":0,"emvCancellations":0,"readerSn":1599082323,"readerVersion":303,"rfu":0,"dnsErrors":0,"diskWriteFail":0,"diskReadFail":0,"emvConfirmations":0,"samErrors":0,"samResets":1,"samTtc":0,"samVersion":14356,"sessionUnifiedAdded":0,"sessionUnifiedRemoved":0,"sessionUnifiedUpdated":0,"size":477,"slsServerHit":7774,"startTime":1663283264,"tcpConnections":1,"tcpErrors":0,"tcpRetries":0,"timestamp":1663291035,"tlsHandshakeErrors":0,"transactionSuccess":0,"bytesSent":184,"emvTransactions":0,"unifiedListItems":0,"unsyncedMismatchCount":0,"updateServerStatus":1,"virtualStatus":0,"virtualTransactions":0,"bytesReceived":69,"avrListItems":0,"vlibUptime":7771,"avrGlobalCount":0,"abtTransactions":0,"vreadyStatus":1} | br.inf.planeta.services.OneSecService$4 (run line: 685) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
EXCEPTION | 2022-09-15 22:17:42 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-15 22:17:42 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
EXCEPTION | 2022-09-15 22:18:00 | <<<--- | Erro ao obter hora de Servidor NTP: null[libcore.io.IoBridge.maybeThrowAfterRecvfrom(IoBridge.java:551), libcore.io.IoBridge.recvfrom(IoBridge.java:509), java.net.PlainDatagramSocketImpl.doRecv(PlainDatagramSocketImpl.java:161), java.net.PlainDatagramSocketImpl.receive(PlainDatagramSocketImpl.java:169), java.net.DatagramSocket.receive(DatagramSocket.java:250), org.apache.commons.net.ntp.NTPUDPClient.getTime(NTPUDPClient.java:89), br.inf.planeta.pedagio.DateTimeNTPServer.setSystemDateTimeWithDateTimeFromNTPServer(DateTimeNTPServer.java:25), br.inf.planeta.services.OneSecService$1.run(OneSecService.java:189), java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422), java.util.concurrent.FutureTask.run(FutureTask.java:237), java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152), java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | br.inf.planeta.services.OneSecService$1 (run line: 189) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (run line: 237)
ETH_LOG | 2022-09-15 22:18:01 | Eth OK | br.inf.planeta.services.OneSecService$4 (run line: 685) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
REST | 2022-09-15 22:18:10 | --->>> | Response: {"VersaoSoftware":"9.6.5","Antenas":[{"VersaoSoftware":"0000012F","NomeLeitor":"SCR916","NumeroSerieLeitor":"5F500F53","NumLeitor":0,"BlStatusLeitor":1}],"ContadoresInternos":[0,0],"DataHora":"2022-09-15 22:18:10","NumeroSerieSLM":"8000B0CC","SLMTempoExecucao":7841,"AndroidTempoExecucao":7864} | br.inf.planeta.services.OneSecService$4 (run line: 685) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
EXCEPTION | 2022-09-15 22:18:13 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-15 22:18:13 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
EXCEPTION | 2022-09-15 22:18:44 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
EXCEPTION | 2022-09-15 22:18:44 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
ETH_LOG | 2022-09-15 22:19:01 | Eth OK | br.inf.planeta.services.OneSecService$4 (run line: 685) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
EXCEPTION | 2022-09-15 22:19:15 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-15 22:19:15 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
EXCEPTION | 2022-09-15 22:19:46 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-15 22:19:46 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
ETH_LOG | 2022-09-15 22:20:02 | Eth OK | br.inf.planeta.services.OneSecService$4 (run line: 685) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
EXCEPTION | 2022-09-15 22:20:16 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-15 22:20:16 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
EXCEPTION | 2022-09-15 22:20:47 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-15 22:20:47 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
ETH_LOG | 2022-09-15 22:21:03 | Eth OK | br.inf.planeta.services.OneSecService$4 (run line: 685) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
EXCEPTION | 2022-09-15 22:21:17 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-15 22:21:17 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
EXCEPTION | 2022-09-15 22:21:48 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-15 22:21:48 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
ETH_LOG | 2022-09-15 22:22:04 | Eth OK | br.inf.planeta.services.OneSecService$4 (run line: 685) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
EXCEPTION | 2022-09-15 22:22:19 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-15 22:22:19 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
EXCEPTION | 2022-09-15 22:22:49 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-15 22:22:49 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
EXCEPTION | 2022-09-15 22:23:01 | <<<--- | Erro ao obter hora de Servidor NTP: null[libcore.io.IoBridge.maybeThrowAfterRecvfrom(IoBridge.java:551), libcore.io.IoBridge.recvfrom(IoBridge.java:509), java.net.PlainDatagramSocketImpl.doRecv(PlainDatagramSocketImpl.java:161), java.net.PlainDatagramSocketImpl.receive(PlainDatagramSocketImpl.java:169), java.net.DatagramSocket.receive(DatagramSocket.java:250), org.apache.commons.net.ntp.NTPUDPClient.getTime(NTPUDPClient.java:89), br.inf.planeta.pedagio.DateTimeNTPServer.setSystemDateTimeWithDateTimeFromNTPServer(DateTimeNTPServer.java:25), br.inf.planeta.services.OneSecService$1.run(OneSecService.java:189), java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422), java.util.concurrent.FutureTask.run(FutureTask.java:237), java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152), java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | br.inf.planeta.services.OneSecService$1 (run line: 189) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (run line: 237)
ETH_LOG | 2022-09-15 22:23:05 | Eth OK | br.inf.planeta.services.OneSecService$4 (run line: 685) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
REST | 2022-09-15 22:23:11 | --->>> | Response: {"VersaoSoftware":"9.6.5","Antenas":[{"VersaoSoftware":"0000012F","NomeLeitor":"SCR916","NumeroSerieLeitor":"5F500F53","NumLeitor":0,"BlStatusLeitor":1}],"ContadoresInternos":[0,0],"DataHora":"2022-09-15 22:23:11","NumeroSerieSLM":"8000B0CC","SLMTempoExecucao":8142,"AndroidTempoExecucao":8165} | br.inf.planeta.services.OneSecService$4 (run line: 685) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
EXCEPTION | 2022-09-15 22:23:19 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-15 22:23:19 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
EXCEPTION | 2022-09-15 22:23:50 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-15 22:23:50 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
ETH_LOG | 2022-09-15 22:24:06 | Eth OK | br.inf.planeta.services.OneSecService$4 (run line: 685) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
EXCEPTION | 2022-09-15 22:24:21 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-15 22:24:21 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
EXCEPTION | 2022-09-15 22:24:51 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-15 22:24:51 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
ETH_LOG | 2022-09-15 22:25:07 | Eth OK | br.inf.planeta.services.OneSecService$4 (run line: 685) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
EXCEPTION | 2022-09-15 22:25:22 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-15 22:25:22 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
EXCEPTION | 2022-09-15 22:25:52 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-15 22:25:52 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
ETH_LOG | 2022-09-15 22:26:08 | Eth OK | br.inf.planeta.services.OneSecService$4 (run line: 685) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
EXCEPTION | 2022-09-15 22:26:23 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-15 22:26:23 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
EXCEPTION | 2022-09-15 22:26:54 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-15 22:26:54 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
ETH_LOG | 2022-09-15 22:27:09 | Eth OK | br.inf.planeta.services.OneSecService$4 (run line: 685) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
DAILY_STATS | 2022-09-15 22:27:16 | {} | br.inf.planeta.services.OneSecService$4 (run line: 685) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)

VLIB_SESSION_STATS | 2022-09-15 22:27:16 | {"vmeshVersionStr":"","vlibVersionStr":"1.2.0-global","vlibId":"","vlibGitVersion":"4749542076657273696F6E206E6F7420617661696C61626C652100000000000000000000000000000000","ulibVersionStr":"1.0.1","samCsn":"58434C0062E15DF9","samBuildTime":"23:10:19","samBuildDate":"Nov 12 2019","samAtr":"3B1D97434C5F53414D00143800009000","readerModel":"SCR916","enabledKernelApps":[0,6,6,6,0,0,0,0,0,0,0,0,0,0,0,0],"emvSamConfig":"3000010545434F39","unifiedControlRequest":0,"configControlRequest":0,"enabledKernelBits":67108878,"httpReuses":0,"lastPspData":0,"lastSlsData":1663283261,"listFlags":134217732,"onlineTimeout":-8372,"pspErrors":0,"pspServerHit":0,"pspServerStatus":0,"pspUrlIndex":0,"qrcodeTransactions":0,"readerErrors":0,"emvCancellations":0,"readerSn":1599082323,"readerVersion":303,"rfu":0,"dnsErrors":0,"diskWriteFail":0,"diskReadFail":0,"emvConfirmations":0,"samErrors":0,"samResets":1,"samTtc":0,"samVersion":14356,"sessionUnifiedAdded":0,"sessionUnifiedRemoved":0,"sessionUnifiedUpdated":0,"size":477,"slsServerHit":8375,"startTime":1663283264,"tcpConnections":1,"tcpErrors":0,"tcpRetries":0,"timestamp":1663291636,"tlsHandshakeErrors":0,"transactionSuccess":0,"bytesSent":184,"emvTransactions":0,"unifiedListItems":0,"unsyncedMismatchCount":0,"updateServerStatus":1,"virtualStatus":0,"virtualTransactions":0,"bytesReceived":69,"avrListItems":0,"vlibUptime":8372,"avrGlobalCount":0,"abtTransactions":0,"vreadyStatus":1} | br.inf.planeta.services.OneSecService$4 (run line: 685) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
EXCEPTION | 2022-09-15 22:27:25 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-15 22:27:25 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
EXCEPTION | 2022-09-15 22:27:55 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-15 22:27:55 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
EXCEPTION | 2022-09-15 22:28:01 | <<<--- | Erro ao obter hora de Servidor NTP: null[libcore.io.IoBridge.maybeThrowAfterRecvfrom(IoBridge.java:551), libcore.io.IoBridge.recvfrom(IoBridge.java:509), java.net.PlainDatagramSocketImpl.doRecv(PlainDatagramSocketImpl.java:161), java.net.PlainDatagramSocketImpl.receive(PlainDatagramSocketImpl.java:169), java.net.DatagramSocket.receive(DatagramSocket.java:250), org.apache.commons.net.ntp.NTPUDPClient.getTime(NTPUDPClient.java:89), br.inf.planeta.pedagio.DateTimeNTPServer.setSystemDateTimeWithDateTimeFromNTPServer(DateTimeNTPServer.java:25), br.inf.planeta.services.OneSecService$1.run(OneSecService.java:189), java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422), java.util.concurrent.FutureTask.run(FutureTask.java:237), java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152), java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | br.inf.planeta.services.OneSecService$1 (run line: 189) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (run line: 237)
ETH_LOG | 2022-09-15 22:28:10 | Eth OK | br.inf.planeta.services.OneSecService$4 (run line: 685) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
REST | 2022-09-15 22:28:12 | --->>> | Response: {"VersaoSoftware":"9.6.5","Antenas":[{"VersaoSoftware":"0000012F","NomeLeitor":"SCR916","NumeroSerieLeitor":"5F500F53","NumLeitor":0,"BlStatusLeitor":1}],"ContadoresInternos":[0,0],"DataHora":"2022-09-15 22:28:12","NumeroSerieSLM":"8000B0CC","SLMTempoExecucao":8444,"AndroidTempoExecucao":8466} | br.inf.planeta.services.OneSecService$4 (run line: 685) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
EXCEPTION | 2022-09-15 22:28:26 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-15 22:28:26 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
EXCEPTION | 2022-09-15 22:28:56 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-15 22:28:56 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
ETH_LOG | 2022-09-15 22:29:11 | Eth OK | br.inf.planeta.services.OneSecService$4 (run line: 685) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
EXCEPTION | 2022-09-15 22:29:27 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-15 22:29:27 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
EXCEPTION | 2022-09-15 22:29:57 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-15 22:29:57 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
ETH_LOG | 2022-09-15 22:30:12 | Eth OK | br.inf.planeta.services.OneSecService$4 (run line: 685) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
EXCEPTION | 2022-09-15 22:30:28 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-15 22:30:28 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
EXCEPTION | 2022-09-15 22:30:59 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-15 22:30:59 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
ETH_LOG | 2022-09-15 22:31:13 | Eth OK | br.inf.planeta.services.OneSecService$4 (run line: 685) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
EXCEPTION | 2022-09-15 22:31:29 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-15 22:31:29 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
EXCEPTION | 2022-09-15 22:32:00 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-15 22:32:00 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
ETH_LOG | 2022-09-15 22:32:14 | Eth OK | br.inf.planeta.services.OneSecService$4 (run line: 685) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
EXCEPTION | 2022-09-15 22:32:30 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-15 22:32:30 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
EXCEPTION | 2022-09-15 22:33:00 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-15 22:33:00 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
EXCEPTION | 2022-09-15 22:33:02 | <<<--- | Erro ao obter hora de Servidor NTP: null[libcore.io.IoBridge.maybeThrowAfterRecvfrom(IoBridge.java:551), libcore.io.IoBridge.recvfrom(IoBridge.java:509), java.net.PlainDatagramSocketImpl.doRecv(PlainDatagramSocketImpl.java:161), java.net.PlainDatagramSocketImpl.receive(PlainDatagramSocketImpl.java:169), java.net.DatagramSocket.receive(DatagramSocket.java:250), org.apache.commons.net.ntp.NTPUDPClient.getTime(NTPUDPClient.java:89), br.inf.planeta.pedagio.DateTimeNTPServer.setSystemDateTimeWithDateTimeFromNTPServer(DateTimeNTPServer.java:25), br.inf.planeta.services.OneSecService$1.run(OneSecService.java:189), java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422), java.util.concurrent.FutureTask.run(FutureTask.java:237), java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152), java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | br.inf.planeta.services.OneSecService$1 (run line: 189) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (run line: 237)
REST | 2022-09-15 22:33:13 | --->>> | Response: {"VersaoSoftware":"9.6.5","Antenas":[{"VersaoSoftware":"0000012F","NomeLeitor":"SCR916","NumeroSerieLeitor":"5F500F53","NumLeitor":0,"BlStatusLeitor":1}],"ContadoresInternos":[0,0],"DataHora":"2022-09-15 22:33:13","NumeroSerieSLM":"8000B0CC","SLMTempoExecucao":8745,"AndroidTempoExecucao":8768} | br.inf.planeta.services.OneSecService$4 (run line: 685) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
ETH_LOG | 2022-09-15 22:33:15 | Eth OK | br.inf.planeta.services.OneSecService$4 (run line: 685) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
EXCEPTION | 2022-09-15 22:33:31 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-15 22:33:31 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
EXCEPTION | 2022-09-15 22:34:01 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-15 22:34:01 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
ETH_LOG | 2022-09-15 22:34:16 | Eth OK | br.inf.planeta.services.OneSecService$4 (run line: 685) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
EXCEPTION | 2022-09-15 22:34:32 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-15 22:34:32 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
EXCEPTION | 2022-09-15 22:35:02 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-15 22:35:02 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
ETH_LOG | 2022-09-15 22:35:17 | Eth OK | br.inf.planeta.services.OneSecService$4 (run line: 685) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
EXCEPTION | 2022-09-15 22:35:32 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-15 22:35:32 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
EXCEPTION | 2022-09-15 22:36:02 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-15 22:36:02 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
ETH_LOG | 2022-09-15 22:36:18 | Eth OK | br.inf.planeta.services.OneSecService$4 (run line: 685) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
EXCEPTION | 2022-09-15 22:36:33 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-15 22:36:33 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
EXCEPTION | 2022-09-15 22:37:03 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-15 22:37:03 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
DAILY_STATS | 2022-09-15 22:37:17 | {} | br.inf.planeta.services.OneSecService$4 (run line: 685) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)

VLIB_SESSION_STATS | 2022-09-15 22:37:17 | {"vmeshVersionStr":"","vlibVersionStr":"1.2.0-global","vlibId":"","vlibGitVersion":"4749542076657273696F6E206E6F7420617661696C61626C652100000000000000000000000000000000","ulibVersionStr":"1.0.1","samCsn":"58434C0062E15DF9","samBuildTime":"23:10:19","samBuildDate":"Nov 12 2019","samAtr":"3B1D97434C5F53414D00143800009000","readerModel":"SCR916","enabledKernelApps":[0,6,6,6,0,0,0,0,0,0,0,0,0,0,0,0],"emvSamConfig":"3000010545434F39","unifiedControlRequest":0,"configControlRequest":0,"enabledKernelBits":67108878,"httpReuses":0,"lastPspData":0,"lastSlsData":1663283261,"listFlags":134217732,"onlineTimeout":-8973,"pspErrors":0,"pspServerHit":0,"pspServerStatus":0,"pspUrlIndex":0,"qrcodeTransactions":0,"readerErrors":0,"emvCancellations":0,"readerSn":1599082323,"readerVersion":303,"rfu":0,"dnsErrors":0,"diskWriteFail":0,"diskReadFail":0,"emvConfirmations":0,"samErrors":0,"samResets":1,"samTtc":0,"samVersion":14356,"sessionUnifiedAdded":0,"sessionUnifiedRemoved":0,"sessionUnifiedUpdated":0,"size":477,"slsServerHit":8976,"startTime":1663283264,"tcpConnections":1,"tcpErrors":0,"tcpRetries":0,"timestamp":1663292237,"tlsHandshakeErrors":0,"transactionSuccess":0,"bytesSent":184,"emvTransactions":0,"unifiedListItems":0,"unsyncedMismatchCount":0,"updateServerStatus":1,"virtualStatus":0,"virtualTransactions":0,"bytesReceived":69,"avrListItems":0,"vlibUptime":8973,"avrGlobalCount":0,"abtTransactions":0,"vreadyStatus":1} | br.inf.planeta.services.OneSecService$4 (run line: 685) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
ETH_LOG | 2022-09-15 22:37:19 | Eth OK | br.inf.planeta.services.OneSecService$4 (run line: 685) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
EXCEPTION | 2022-09-15 22:37:34 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-15 22:37:34 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
EXCEPTION | 2022-09-15 22:38:03 | <<<--- | Erro ao obter hora de Servidor NTP: null[libcore.io.IoBridge.maybeThrowAfterRecvfrom(IoBridge.java:551), libcore.io.IoBridge.recvfrom(IoBridge.java:509), java.net.PlainDatagramSocketImpl.doRecv(PlainDatagramSocketImpl.java:161), java.net.PlainDatagramSocketImpl.receive(PlainDatagramSocketImpl.java:169), java.net.DatagramSocket.receive(DatagramSocket.java:250), org.apache.commons.net.ntp.NTPUDPClient.getTime(NTPUDPClient.java:89), br.inf.planeta.pedagio.DateTimeNTPServer.setSystemDateTimeWithDateTimeFromNTPServer(DateTimeNTPServer.java:25), br.inf.planeta.services.OneSecService$1.run(OneSecService.java:189), java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422), java.util.concurrent.FutureTask.run(FutureTask.java:237), java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152), java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | br.inf.planeta.services.OneSecService$1 (run line: 189) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (run line: 237)
EXCEPTION | 2022-09-15 22:38:04 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

